/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author jashw
 */
public class chart extends javax.swing.JFrame {
    static Connection con;
    
    /**
     * Creates new form chart
     */
    public chart() {
        initComponents();
        
        
        try{  
        Class.forName("com.mysql.jdbc.Driver");  
        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/voterdb","root","jay1968$"); 
        
        

}catch(Exception e){ System.out.println(e);}
        
        
        
        DefaultPieDataset dataset = new DefaultPieDataset( );
        try {
            PreparedStatement p = con.prepareStatement("select * from votes where cons = ?");
            p.setObject(1,Global.x1);
            ResultSet rs = p.executeQuery();
            rs.beforeFirst();
            while(rs.next())
            {
                PreparedStatement p2 = con.prepareStatement("select count(aadhar) as count from votes where candidate = ?");
                p2.setString(1, rs.getString("candidate"));
                ResultSet rs2 = p2.executeQuery();
                rs2.beforeFirst();
                while (rs2.next())
                    dataset.setValue( rs.getString("candidate"), rs2.getInt("count"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(chart.class.getName()).log(Level.SEVERE, null, ex);
        }  
    
      JFreeChart chart = ChartFactory.createPieChart("Votes",  dataset, true, true,false);  
    
      ChartPanel panel = new ChartPanel(chart);  
      setContentPane(panel);   
      panel.setBounds(50, 50, 50, 50);
       
   }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      chart demo = new chart();  
      demo.setSize(100, 100);   
       
      demo.setVisible( true ); 
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
