/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.lang.Math;

/**'
 *
 * @author jashw
 */
public class turnout extends javax.swing.JFrame {
    Connection con;

    /**
     * Creates new form turnout
     */
    public turnout() {
        initComponents();
        
        try{  
        Class.forName("com.mysql.jdbc.Driver");  
        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/voterdb","root","jay1968$"); 
        PreparedStatement p1 = con.prepareStatement("select distinct conno as conno from voter");
        ResultSet rs;
        rs = p1.executeQuery();
        rs.beforeFirst();
        while(rs.next())
        {  
            conno.addItem(Integer.toString(rs.getInt("conno")));
        }
            
        }
        
        catch(ClassNotFoundException | SQLException e){
                System.out.println(e);
                }
        
        total.setText("");
        voted.setText("");
        turn.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        voted = new javax.swing.JTextField();
        turn = new javax.swing.JTextField();
        conno = new javax.swing.JComboBox<>();
        report = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TURNOUT");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("CONSTITUENCY");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("TOTAL");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("VOTED");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("% TURNOUT");

        total.setEditable(false);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        voted.setEditable(false);
        voted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votedActionPerformed(evt);
            }
        });

        turn.setEditable(false);
        turn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnActionPerformed(evt);
            }
        });

        conno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connoActionPerformed(evt);
            }
        });

        report.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        report.setText("REPORT");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(voted)
                    .addComponent(total, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turn)
                    .addComponent(conno, 0, 99, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(conno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(voted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(turn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connoActionPerformed
        // TODO add your handling code here:
        int x = 0;
        int y = 0;
        int w = 0;
        int z = 0;
        try {
            // TODO add your handling code here:
            
            PreparedStatement p =con.prepareStatement("select count(vaadhar) as count from voter where conno = ?");
            p.setObject(1, conno.getSelectedItem());
            ResultSet r = p.executeQuery(); 
            while(r.next())
                z= r.getInt("count");
            
            PreparedStatement p3 =con.prepareStatement("select count(caadhar) as count from candidate where vcno = ?");
            p3.setObject(1, conno.getSelectedItem());
            ResultSet r3 = p3.executeQuery(); 
            while(r3.next())
                y= r3.getInt("count");
            
            total.setText(Integer.toString(z+y));
        
            PreparedStatement p1 =con.prepareStatement("select count(vaadhar) as count from voter where conno = ? && vstatus= 1");  
            p1.setObject(1, conno.getSelectedItem());
            ResultSet r1 = p1.executeQuery();
            while(r1.next())
                x= r1.getInt("count");
            
            PreparedStatement p2 =con.prepareStatement("select count(caadhar) as count from candidate where vcno = ? && cstatus= 1");    
            p2.setObject(1, conno.getSelectedItem());
            ResultSet r2 = p2.executeQuery();
            while(r2.next())
                w= r2.getInt("count");
            
            voted.setText(Integer.toString(w+x));
            
       
        int a= Integer.parseInt(total.getText());
        int b= Integer.parseInt(voted.getText());
        float t = (float) (b/(double)a);
        
        turn.setText(Float.toString(t * 100));
        
        PreparedStatement ps = con.prepareStatement("insert into turnout values (?,?,?,?)");
        ps.setObject(1, conno.getSelectedItem());
        ps.setInt(2, Integer.parseInt(total.getText()));
        ps.setInt(3, Integer.parseInt(voted.getText()));
        ps.setFloat(4, Float.parseFloat(turn.getText()));
        ps.execute();

        
        
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_connoActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        
        
    }//GEN-LAST:event_totalActionPerformed

    private void votedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votedActionPerformed
        
    }//GEN-LAST:event_votedActionPerformed

    private void turnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnActionPerformed

        
        
    }//GEN-LAST:event_turnActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
this.dispose();
report rp = new report();
rp.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_reportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(turnout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(turnout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(turnout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(turnout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new turnout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> conno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton report;
    private javax.swing.JTextField total;
    private javax.swing.JTextField turn;
    private javax.swing.JTextField voted;
    // End of variables declaration//GEN-END:variables
}
