package system;


import com.mysql.jdbc.StringUtils;
import com.sun.glass.events.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author csea4024
 */
public class vlogin extends javax.swing.JFrame {

    /**
     * Creates new form vlogin
     */
    Connection con;
    PreparedStatement p1;
    PreparedStatement p2;
    PreparedStatement ps;
    PreparedStatement ps1;
    
    public vlogin() {
        initComponents();
        try{  
        Class.forName("com.mysql.jdbc.Driver");  
        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/voterdb","root","jay1968$"); 
        Statement s=(Statement) con.createStatement();          

}catch(Exception e){ System.out.println(e);}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        vaadhar = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        vlogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        vsignup = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("VOTER LOGIN");

        username.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        username.setText("AADHAR NO");

        vaadhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vaadharKeyPressed(evt);
            }
        });

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        vlogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vlogin.setText("LOGIN");
        vlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vloginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("NEW USER?");

        vsignup.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vsignup.setText("SIGN UP");
        vsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsignupActionPerformed(evt);
            }
        });

        home.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("PASSWORD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addComponent(vlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(vaadhar, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(password))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(vsignup)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vloginActionPerformed
                                                          // TODO add your handling code here:            
            try{
                ps = con.prepareStatement("select * from voter where vaadhar = ? && password = ?");
                if(StringUtils.isNullOrEmpty(vaadhar.getText()) || StringUtils.isNullOrEmpty(password.getText()))
                    JOptionPane.showMessageDialog(this,"No Data..!!");
                else
                {
                    ps.setInt(1,Integer.parseInt(vaadhar.getText()));
                    ps.setString(2, password.getText());
                    
                    ResultSet rs = ps.executeQuery();
                    
                    if(rs.next()==false)
                    {
                        JOptionPane.showMessageDialog(this,"Invalid Voter..!!");
                        vaadhar.setText("");
                        password.setText("");
                    }
                    else
                    {
                        ps1 = con.prepareStatement("select vstatus as s from voter where vaadhar = ?");
                        ps1.setInt(1, Integer.parseInt(vaadhar.getText()));
                        ResultSet r1 = ps1.executeQuery();
                        r1.next();
                        int x = r1.getInt("s");
                        if(x==0)
                        {
                            Global.vano = Integer.parseInt(vaadhar.getText());
                            Global.cano = 0;
                            p1 = con.prepareStatement("select conno as c from voter where vaadhar = ?");
                            p1.setInt(1,Integer.parseInt(vaadhar.getText()));
                            ResultSet r = p1.executeQuery();
                            r.beforeFirst();
                            r.next();
                            Global.vcon = r.getInt("c");
                            Global.ccon = 0;                      
                            
                        
                            this.dispose();
                            vote v = new vote();
                            v.setVisible(true);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this,"Vote Registered Aldready...!!!");
                            this.dispose();
                            home h = new home();
                            h.setVisible(true);
                        }
                    }
                }
                
            }
            catch(Exception e)
            {
                Logger.getLogger(clogin.class.getName()).log(Level.SEVERE, null, e);
            }
            

            
           
    }//GEN-LAST:event_vloginActionPerformed

    private void vsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsignupActionPerformed
        // TODO add your handling code here:
        this.dispose();
        vsignup vs = new vsignup();
        vs.setVisible(true);
    }//GEN-LAST:event_vsignupActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
this.dispose();
home h = new home();
h.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try{
                ps = con.prepareStatement("select * from voter where vaadhar = ? && password = ?");
                if(StringUtils.isNullOrEmpty(vaadhar.getText()) || StringUtils.isNullOrEmpty(password.getText()))
                    JOptionPane.showMessageDialog(this,"No Data..!!");
                else
                {
                    ps.setInt(1,Integer.parseInt(vaadhar.getText()));
                    ps.setString(2, password.getText());
                    
                    ResultSet rs = ps.executeQuery();
                    
                    if(rs.next()==false)
                    {
                        JOptionPane.showMessageDialog(this,"Invalid Voter..!!");
                        vaadhar.setText("");
                        password.setText("");
                    }
                    else
                    {
                        ps1 = con.prepareStatement("select status as s from voter where vaadhar = ?");
                        ps1.setInt(1, Integer.parseInt(vaadhar.getText()));
                        ResultSet r1 = ps1.executeQuery();
                        r1.next();
                        int x = r1.getInt("s");
                        if(x==0)
                        {
                            Global.vano = Integer.parseInt(vaadhar.getText());
                            Global.cano = 0;
                            p1 = con.prepareStatement("select conno as c from voter where vaadhar = ?");
                            p1.setInt(1,Integer.parseInt(vaadhar.getText()));
                            ResultSet r = p1.executeQuery();
                            r.beforeFirst();
                            r.next();
                            Global.vcon = r.getInt("c");
                            Global.ccon = 0;                      
                            
                        
                            this.dispose();
                            vote v = new vote();
                            v.setVisible(true);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this,"Vote Registered Aldready...!!!");
                            this.dispose();
                            home h = new home();
                            h.setVisible(true);
                        }
                    }
                }
            }
            catch(Exception e)
            {
                Logger.getLogger(clogin.class.getName()).log(Level.SEVERE, null, e);
            }
            

            
            
        }    
    }//GEN-LAST:event_passwordKeyPressed

    private void vaadharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vaadharKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
             password.requestFocus();
         }
    }//GEN-LAST:event_vaadharKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel username;
    private javax.swing.JTextField vaadhar;
    private javax.swing.JButton vlogin;
    private javax.swing.JButton vsignup;
    // End of variables declaration//GEN-END:variables

    private boolean isNullorEmpty(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
